{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPublishAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/channelparams\/allowpublishaudio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/aircoremedia\/channelparams\/allowpublishaudio"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelParams\/allowPublishAudio","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Toggles audio publish permissions for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"},{"type":"text","text":" objects created by this "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel"},{"type":"text","text":", defaults to "},{"type":"codeVoice","code":"true"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPublishAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"allowPublishAudio","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@AircoreMedia@objc(cs)AIRChannelParams(py)allowPublishAudio","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"allowPublishAudio"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelParams"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/ChannelParams/allowPublishAudio":{"role":"symbol","title":"allowPublishAudio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPublishAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Toggles audio publish permissions for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"},{"type":"text","text":" objects created by this "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel"},{"type":"text","text":", defaults to "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelParams\/allowPublishAudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowPublishAudio"}],"url":"\/documentation\/aircoremedia\/channelparams\/allowpublishaudio"},"doc://io.aircore.media/documentation/AircoreMedia/ChannelParams":{"role":"symbol","title":"ChannelParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelParams"}],"abstract":[{"type":"text","text":"An object representing configurations for a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel"},{"type":"text","text":" object"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelParams"}],"url":"\/documentation\/aircoremedia\/channelparams"},"doc://io.aircore.media/documentation/AircoreMedia/Channel":{"role":"symbol","title":"Channel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Channel"}],"abstract":[{"type":"text","text":"An object representing a connection to a streaming context"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Channel"}],"url":"\/documentation\/aircoremedia\/channel"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/LocalStream":{"role":"symbol","title":"LocalStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalStream"}],"abstract":[{"type":"text","text":"An object representing a local stream that sends audio"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalStream"}],"url":"\/documentation\/aircoremedia\/localstream"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"allowPublishAudio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"allowPublishAudio"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPublishAudio"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1ChannelParams~1allowPublishAudio\/title","value":"allowPublishAudio"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1ChannelParams~1allowPublishAudio\/fragments","value":[{"kind":"identifier","text":"allowPublishAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1ChannelParams\/title","value":"AIRChannelParams"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1ChannelParams\/fragments","value":[{"kind":"identifier","text":"AIRChannelParams"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Channel\/title","value":"AIRChannel"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Channel\/fragments","value":[{"kind":"identifier","text":"AIRChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/title","value":"AIRLocalStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/fragments","value":[{"kind":"identifier","text":"AIRLocalStream"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}