{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputVolume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Values are constrained on the interval [0,1]."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can change this value at any time."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/channel\/outputvolume"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/aircoremedia\/channel\/outputvolume"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel\/outputVolume","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The output volume for the channel as a fraction of full volume. Defaults to 1 (full volume)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputVolume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"outputVolume","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@AircoreMedia@objc(cs)AIRChannel(py)outputVolume","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"outputVolume"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/Channel/outputVolume":{"role":"symbol","title":"outputVolume","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputVolume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The output volume for the channel as a fraction of full volume. Defaults to 1 (full volume)."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel\/outputVolume","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"outputVolume"}],"url":"\/documentation\/aircoremedia\/channel\/outputvolume"},"doc://io.aircore.media/documentation/AircoreMedia/Channel":{"role":"symbol","title":"Channel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Channel"}],"abstract":[{"type":"text","text":"An object representing a connection to a streaming context"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Channel"}],"url":"\/documentation\/aircoremedia\/channel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"outputVolume"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"outputVolume"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputVolume"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Channel~1outputVolume\/title","value":"outputVolume"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Channel~1outputVolume\/fragments","value":[{"kind":"identifier","text":"outputVolume"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Channel\/title","value":"AIRChannel"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Channel\/fragments","value":[{"kind":"identifier","text":"AIRChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}