{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/localstreamparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStreamParams\/init","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AircoreMedia@objc(cs)AIRLocalStreamParams(im)init","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStreamParams"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/LocalStreamParams/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStreamParams\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/aircoremedia\/localstreamparams\/init"},"doc://io.aircore.media/documentation/AircoreMedia/LocalStream":{"role":"symbol","title":"LocalStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalStream"}],"abstract":[{"type":"text","text":"An object representing a local stream that sends audio"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalStream"}],"url":"\/documentation\/aircoremedia\/localstream"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/LocalStreamParams":{"role":"symbol","title":"LocalStreamParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalStreamParams"}],"abstract":[{"type":"text","text":"An object representing configurations for a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"},{"type":"text","text":" object."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStreamParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalStreamParams"}],"url":"\/documentation\/aircoremedia\/localstreamparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/title","value":"AIRLocalStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/fragments","value":[{"kind":"identifier","text":"AIRLocalStream"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStreamParams\/title","value":"AIRLocalStreamParams"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStreamParams\/fragments","value":[{"kind":"identifier","text":"AIRLocalStreamParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}