{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/ResolutionPreset","preciseIdentifier":"s:12AircoreMedia6CameraC16ResolutionPresetC","text":"ResolutionPreset"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"preset: The preset resolution as a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/ResolutionPreset"},{"type":"text","text":"."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The preset given will provide two enum values:"},{"type":"text","text":" "},{"type":"text","text":"quality, a value of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/Quality"},{"type":"text","text":", and"},{"type":"text","text":" "},{"type":"text","text":"aspectRatio, a value of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/AspectRatio"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If an unknown case of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/Quality"},{"type":"text","text":" is provided, the default of 720p will be used."},{"type":"text","text":" "},{"type":"text","text":"If an unknown case of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/AspectRatio"},{"type":"text","text":" isProvided, the default square aspect ratio will be used."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/camera\/setpreferredresolution(preset:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/aircoremedia\/camera\/setpreferredresolution(preset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/setPreferredResolution(preset:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the preferred resolution of captured video with a preset."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResolutionPreset","preciseIdentifier":"s:12AircoreMedia6CameraC16ResolutionPresetC"},{"kind":"text","text":")"}],"title":"setPreferredResolution(preset:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AircoreMedia@objc(cs)AIRCamera(im)setPreferredResolutionWithPreset:","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"setPreferredResolutionWithPreset:"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/Camera/AspectRatio":{"role":"symbol","title":"Camera.AspectRatio","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AspectRatio"}],"abstract":[{"type":"text","text":"Aspect ratio of a resolution preset"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/AspectRatio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AspectRatio"}],"url":"\/documentation\/aircoremedia\/camera\/aspectratio"},"doc://io.aircore.media/documentation/AircoreMedia/Camera/ResolutionPreset":{"role":"symbol","title":"Camera.ResolutionPreset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResolutionPreset"}],"abstract":[{"type":"text","text":"Presets for preferred resolution"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/ResolutionPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResolutionPreset"}],"url":"\/documentation\/aircoremedia\/camera\/resolutionpreset"},"doc://io.aircore.media/documentation/AircoreMedia/LocalStream":{"role":"symbol","title":"LocalStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalStream"}],"abstract":[{"type":"text","text":"An object representing a local stream that sends audio"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalStream"}],"url":"\/documentation\/aircoremedia\/localstream"},"doc://io.aircore.media/documentation/AircoreMedia/Camera/setPreferredResolution(preset:)":{"role":"symbol","title":"setPreferredResolution(preset:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredResolution"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ResolutionPreset","preciseIdentifier":"s:12AircoreMedia6CameraC16ResolutionPresetC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the preferred resolution of captured video with a preset."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/setPreferredResolution(preset:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPreferredResolutionWithPreset:"}],"url":"\/documentation\/aircoremedia\/camera\/setpreferredresolution(preset:)"},"doc://io.aircore.media/documentation/AircoreMedia/AIRCameraResolutionPreset":{"role":"symbol","title":"AIRCameraResolutionPreset","fragments":[{"kind":"identifier","text":"AIRCameraResolutionPreset"}],"abstract":[{"type":"text","text":"Presets for preferred resolution"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AIRCameraResolutionPreset","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia\/aircameraresolutionpreset"},"doc://io.aircore.media/documentation/AircoreMedia/Camera/Quality":{"role":"symbol","title":"Camera.Quality","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Quality"}],"abstract":[{"type":"text","text":"Quality of a resolution preset"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/Quality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Quality"}],"url":"\/documentation\/aircoremedia\/camera\/quality"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/Camera":{"role":"symbol","title":"Camera","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Camera"}],"abstract":[{"type":"text","text":"A representation of a Camera that can be used for previewing and publishing video for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"},{"type":"text","text":"."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Camera"}],"url":"\/documentation\/aircoremedia\/camera"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setPreferredResolutionWithPreset:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPreferredResolutionWithPreset:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setPreferredResolutionWithPreset:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AIRCameraResolutionPreset","preciseIdentifier":"c:@M@AircoreMedia@objc(cs)AIRCameraResolutionPreset","text":"AIRCameraResolutionPreset"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/title","value":"AIRLocalStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/fragments","value":[{"kind":"identifier","text":"AIRLocalStream"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Camera~1setPreferredResolution(preset:)\/title","value":"setPreferredResolutionWithPreset:"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Camera~1setPreferredResolution(preset:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPreferredResolutionWithPreset:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Camera\/title","value":"AIRCamera"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Camera\/fragments","value":[{"kind":"identifier","text":"AIRCamera"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}