{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/localstream\/audiomuted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/aircoremedia\/localstream\/audiomuted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream\/audioMuted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether or not the currently recorded audio is muted."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"audioMuted","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@AircoreMedia@objc(cs)AIRLocalStream(py)audioMuted","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"audioMuted"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/LocalStream":{"role":"symbol","title":"LocalStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalStream"}],"abstract":[{"type":"text","text":"An object representing a local stream that sends audio"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalStream"}],"url":"\/documentation\/aircoremedia\/localstream"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/LocalStream/audioMuted":{"role":"symbol","title":"audioMuted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not the currently recorded audio is muted."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream\/audioMuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioMuted"}],"url":"\/documentation\/aircoremedia\/localstream\/audiomuted"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audioMuted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audioMuted"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMuted"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/title","value":"AIRLocalStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/fragments","value":[{"kind":"identifier","text":"AIRLocalStream"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream~1audioMuted\/title","value":"audioMuted"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream~1audioMuted\/fragments","value":[{"kind":"identifier","text":"audioMuted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}