{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/localstream\/stop()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/aircoremedia\/localstream\/stop()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream\/stop()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Terminates the local stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"title":"stop()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AircoreMedia@objc(cs)AIRLocalStream(im)stop","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"stop"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/LocalStream/stop()":{"role":"symbol","title":"stop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Terminates the local stream."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream\/stop()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stop"}],"url":"\/documentation\/aircoremedia\/localstream\/stop()"},"doc://io.aircore.media/documentation/AircoreMedia/LocalStream":{"role":"symbol","title":"LocalStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalStream"}],"abstract":[{"type":"text","text":"An object representing a local stream that sends audio"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalStream"}],"url":"\/documentation\/aircoremedia\/localstream"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stop"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stop"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream~1stop()\/title","value":"stop"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream~1stop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/title","value":"AIRLocalStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/fragments","value":[{"kind":"identifier","text":"AIRLocalStream"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}