{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderTargetHiddenHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"false"},{"type":"text","text":". Set this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the render target is hidden or otherwise not visible,"},{"type":"text","text":" "},{"type":"text","text":"for example if it is contained in an offscreen view hierarchy,"},{"type":"text","text":" "},{"type":"text","text":"or if one of its superviews’ "},{"type":"codeVoice","code":"alpha"},{"type":"text","text":" property is "},{"type":"codeVoice","code":"0"},{"type":"text","text":"."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This property should be accessed from the main thread only."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/remotestream\/rendertargethiddenhint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/aircoremedia\/remotestream\/rendertargethiddenhint"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/renderTargetHiddenHint","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides a hint as to whether the render target provided via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/setRenderTarget(to:)"},{"type":"text","text":" is visible."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderTargetHiddenHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"renderTargetHiddenHint","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@AircoreMedia@objc(cs)AIRRemoteStream(py)renderTargetHiddenHint","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"renderTargetHiddenHint"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/RemoteStream":{"role":"symbol","title":"RemoteStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteStream"}],"abstract":[{"type":"text","text":"An object representing a remote stream"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteStream"}],"url":"\/documentation\/aircoremedia\/remotestream"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/RemoteStream/setRenderTarget(to:)":{"role":"symbol","title":"setRenderTarget(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRenderTarget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Sets a UIView as the render target for remote video stream"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/setRenderTarget(to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRenderTargetTo:"}],"url":"\/documentation\/aircoremedia\/remotestream\/setrendertarget(to:)"},"doc://io.aircore.media/documentation/AircoreMedia/RemoteStream/renderTargetHiddenHint":{"role":"symbol","title":"renderTargetHiddenHint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderTargetHiddenHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Provides a hint as to whether the render target provided via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/setRenderTarget(to:)"},{"type":"text","text":" is visible."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/renderTargetHiddenHint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"renderTargetHiddenHint"}],"url":"\/documentation\/aircoremedia\/remotestream\/rendertargethiddenhint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"renderTargetHiddenHint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"renderTargetHiddenHint"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderTargetHiddenHint"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream\/title","value":"AIRRemoteStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream\/fragments","value":[{"kind":"identifier","text":"AIRRemoteStream"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream~1setRenderTarget(to:)\/title","value":"setRenderTargetTo:"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream~1setRenderTarget(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRenderTargetTo:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream~1renderTargetHiddenHint\/title","value":"renderTargetHiddenHint"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream~1renderTargetHiddenHint\/fragments","value":[{"kind":"identifier","text":"renderTargetHiddenHint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}