{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoHealth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/VideoHealth-swift.enum","preciseIdentifier":"s:12AircoreMedia12RemoteStreamC11VideoHealthO","text":"VideoHealth"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/VideoHealth-swift.enum\/nominal"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/remotestream\/videohealth-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/aircoremedia\/remotestream\/videohealth-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/videoHealth-swift.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The remote stream’s current video health condition."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoHealth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoHealth","preciseIdentifier":"s:12AircoreMedia12RemoteStreamC11VideoHealthO"}],"title":"videoHealth","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@AircoreMedia@objc(cs)AIRRemoteStream(py)videoHealth","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"videoHealth"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/RemoteStream/VideoHealth-swift.enum":{"role":"symbol","title":"RemoteStream.VideoHealth","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoHealth"}],"abstract":[{"type":"text","text":"The video health condition of a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream"},{"type":"text","text":"."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/VideoHealth-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoHealth"}],"url":"\/documentation\/aircoremedia\/remotestream\/videohealth-swift.enum"},"doc://io.aircore.media/documentation/AircoreMedia/AIRRemoteStreamVideoHealth":{"role":"symbol","title":"AIRRemoteStreamVideoHealth","fragments":[{"kind":"identifier","text":"AIRRemoteStreamVideoHealth"}],"abstract":[{"type":"text","text":"The video health condition of a "},{"type":"text","text":"RemoteStream"},{"type":"text","text":"."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AIRRemoteStreamVideoHealth","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia\/airremotestreamvideohealth"},"doc://io.aircore.media/documentation/AircoreMedia/RemoteStream/VideoHealth-swift.enum/nominal":{"role":"symbol","title":"RemoteStream.VideoHealth.nominal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nominal"}],"abstract":[{"type":"text","text":"The video is healthy."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/VideoHealth-swift.enum\/nominal","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia\/remotestream\/videohealth-swift.enum\/nominal"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/RemoteStream":{"role":"symbol","title":"RemoteStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteStream"}],"abstract":[{"type":"text","text":"An object representing a remote stream"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteStream"}],"url":"\/documentation\/aircoremedia\/remotestream"},"doc://io.aircore.media/documentation/AircoreMedia/RemoteStream/videoHealth-swift.property":{"role":"symbol","title":"videoHealth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoHealth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoHealth","preciseIdentifier":"s:12AircoreMedia12RemoteStreamC11VideoHealthO"}],"abstract":[{"type":"text","text":"The remote stream’s current video health condition."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream\/videoHealth-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoHealth"}],"url":"\/documentation\/aircoremedia\/remotestream\/videohealth-swift.property"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoHealth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoHealth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AIRRemoteStreamVideoHealth","preciseIdentifier":"c:@M@AircoreMedia@E@AIRRemoteStreamVideoHealth","text":"AIRRemoteStreamVideoHealth"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoHealth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream\/title","value":"AIRRemoteStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream\/fragments","value":[{"kind":"identifier","text":"AIRRemoteStream"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream~1videoHealth-swift.property\/title","value":"videoHealth"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream~1videoHealth-swift.property\/fragments","value":[{"kind":"identifier","text":"videoHealth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}