{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowest"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/camera\/frameratepreset\/lowest"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/FrameRatePreset\/lowest","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The lowest frame rate preset, 1fps"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowest"}],"title":"Camera.FrameRatePreset.lowest","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12AircoreMedia6CameraC15FrameRatePresetO6lowestyA2EmF","modules":[{"name":"AircoreMedia"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/FrameRatePreset"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/LocalStream":{"role":"symbol","title":"LocalStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalStream"}],"abstract":[{"type":"text","text":"An object representing a local stream that sends audio"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalStream"}],"url":"\/documentation\/aircoremedia\/localstream"},"doc://io.aircore.media/documentation/AircoreMedia/Camera":{"role":"symbol","title":"Camera","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Camera"}],"abstract":[{"type":"text","text":"A representation of a Camera that can be used for previewing and publishing video for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"},{"type":"text","text":"."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Camera"}],"url":"\/documentation\/aircoremedia\/camera"},"doc://io.aircore.media/documentation/AircoreMedia/Camera/FrameRatePreset":{"role":"symbol","title":"Camera.FrameRatePreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FrameRatePreset"}],"abstract":[{"type":"text","text":"Presets for preferred frame rate"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/FrameRatePreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FrameRatePreset"}],"url":"\/documentation\/aircoremedia\/camera\/frameratepreset"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/Camera/FrameRatePreset/lowest":{"role":"symbol","title":"Camera.FrameRatePreset.lowest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowest"}],"abstract":[{"type":"text","text":"The lowest frame rate preset, 1fps"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera\/FrameRatePreset\/lowest","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia\/camera\/frameratepreset\/lowest"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/title","value":"AIRLocalStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/fragments","value":[{"kind":"identifier","text":"AIRLocalStream"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Camera\/title","value":"AIRCamera"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Camera\/fragments","value":[{"kind":"identifier","text":"AIRCamera"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}