{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/audiodeviceconfig\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AudioDeviceConfig\/init","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@AircoreMedia@objc(cs)AIRAudioDeviceConfig(im)init","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AudioDeviceConfig"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/AudioDeviceConfig/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AudioDeviceConfig\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/aircoremedia\/audiodeviceconfig\/init"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/AudioDeviceConfig":{"role":"symbol","title":"AudioDeviceConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioDeviceConfig"}],"abstract":[{"type":"text","text":"The global audio device configuration settings."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AudioDeviceConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioDeviceConfig"}],"url":"\/documentation\/aircoremedia\/audiodeviceconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1AudioDeviceConfig\/title","value":"AIRAudioDeviceConfig"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1AudioDeviceConfig\/fragments","value":[{"kind":"identifier","text":"AIRAudioDeviceConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}