{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameworkVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/engine\/frameworkversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/aircoremedia\/engine\/frameworkversion"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine\/frameworkVersion","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The framework version number."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameworkVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"frameworkVersion","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@AircoreMedia@objc(cs)AIREngine(cpy)frameworkVersion","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"frameworkVersion"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/Engine":{"role":"symbol","title":"Engine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Engine"}],"abstract":[{"type":"text","text":"The singleton class that provides access to global information, settings, and functionality."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Engine"}],"url":"\/documentation\/aircoremedia\/engine"},"doc://io.aircore.media/documentation/AircoreMedia/Engine/frameworkVersion":{"role":"symbol","title":"frameworkVersion","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameworkVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The framework version number."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine\/frameworkVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameworkVersion"}],"url":"\/documentation\/aircoremedia\/engine\/frameworkversion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"frameworkVersion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"frameworkVersion"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"frameworkVersion"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine\/title","value":"AIREngine"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine\/fragments","value":[{"kind":"identifier","text":"AIREngine"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine~1frameworkVersion\/title","value":"frameworkVersion"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine~1frameworkVersion\/fragments","value":[{"kind":"identifier","text":"frameworkVersion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}