{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStreamDebuggingEnabled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether or not to enable stream debugging."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This will have no effect if the directory path for storing logs"},{"type":"text","text":" "},{"type":"text","text":"has not been set with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine\/setLogDirPath(_:)"},{"type":"text","text":"."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/engine\/setstreamdebuggingenabled(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/aircoremedia\/engine\/setstreamdebuggingenabled(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine\/setStreamDebuggingEnabled(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables stream debugging for newly created "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream"},{"type":"text","text":" instances."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setStreamDebuggingEnabled:"}],"role":"symbol","title":"setStreamDebuggingEnabled(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStreamDebuggingEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@AircoreMedia@objc(cs)AIREngine(im)setStreamDebuggingEnabled:","extendedModule":"AircoreMedia","modules":[{"name":"AircoreMedia"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/Engine":{"role":"symbol","title":"Engine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Engine"}],"abstract":[{"type":"text","text":"The singleton class that provides access to global information, settings, and functionality."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Engine"}],"url":"\/documentation\/aircoremedia\/engine"},"doc://io.aircore.media/documentation/AircoreMedia/Engine/setStreamDebuggingEnabled(_:)":{"role":"symbol","title":"setStreamDebuggingEnabled(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStreamDebuggingEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enables stream debugging for newly created "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream"},{"type":"text","text":" instances."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine\/setStreamDebuggingEnabled(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setStreamDebuggingEnabled:"}],"url":"\/documentation\/aircoremedia\/engine\/setstreamdebuggingenabled(_:)"},"doc://io.aircore.media/documentation/AircoreMedia/RemoteStream":{"role":"symbol","title":"RemoteStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteStream"}],"abstract":[{"type":"text","text":"An object representing a remote stream"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/RemoteStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteStream"}],"url":"\/documentation\/aircoremedia\/remotestream"},"doc://io.aircore.media/documentation/AircoreMedia/Engine/setLogDirPath(_:)":{"role":"symbol","title":"setLogDirPath(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogDirPath"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the directory path for where to store logs."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Engine\/setLogDirPath(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLogDirPath:"}],"url":"\/documentation\/aircoremedia\/engine\/setlogdirpath(_:)"},"doc://io.aircore.media/documentation/AircoreMedia/LocalStream":{"role":"symbol","title":"LocalStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalStream"}],"abstract":[{"type":"text","text":"An object representing a local stream that sends audio"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalStream"}],"url":"\/documentation\/aircoremedia\/localstream"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setStreamDebuggingEnabled:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setStreamDebuggingEnabled:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setStreamDebuggingEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine\/title","value":"AIREngine"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine\/fragments","value":[{"kind":"identifier","text":"AIREngine"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine~1setStreamDebuggingEnabled(_:)\/title","value":"setStreamDebuggingEnabled:"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine~1setStreamDebuggingEnabled(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setStreamDebuggingEnabled:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream\/title","value":"AIRRemoteStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1RemoteStream\/fragments","value":[{"kind":"identifier","text":"AIRRemoteStream"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine~1setLogDirPath(_:)\/title","value":"setLogDirPath:"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Engine~1setLogDirPath(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLogDirPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/title","value":"AIRLocalStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/fragments","value":[{"kind":"identifier","text":"AIRLocalStream"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}