{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"newJoinState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/channelnotification\/key\/newjoinstate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification\/Key\/newJoinState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The key to get the new "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel\/JoinState-swift.enum"},{"type":"text","text":" "},{"type":"text","text":"associated with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification\/joinStateDidChange"},{"type":"text","text":" notification."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"newJoinState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"newJoinState","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"s:12AircoreMedia19ChannelNotificationC3KeyC12newJoinStateSSvpZ","modules":[{"name":"AircoreMedia"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification\/Key"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/ChannelNotification/Key/newJoinState":{"role":"symbol","title":"newJoinState","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"newJoinState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The key to get the new "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel\/JoinState-swift.enum"},{"type":"text","text":" "},{"type":"text","text":"associated with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification\/joinStateDidChange"},{"type":"text","text":" notification."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification\/Key\/newJoinState","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia\/channelnotification\/key\/newjoinstate"},"doc://io.aircore.media/documentation/AircoreMedia/ChannelNotification/Key":{"role":"symbol","title":"ChannelNotification.Key","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Key"}],"abstract":[{"type":"text","text":"Keys associated with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"userInfo"},{"type":"text","text":" dictionary."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification\/Key","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Key"}],"url":"\/documentation\/aircoremedia\/channelnotification\/key"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"},"doc://io.aircore.media/documentation/AircoreMedia/Channel":{"role":"symbol","title":"Channel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Channel"}],"abstract":[{"type":"text","text":"An object representing a connection to a streaming context"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Channel"}],"url":"\/documentation\/aircoremedia\/channel"},"doc://io.aircore.media/documentation/AircoreMedia/ChannelNotification":{"role":"symbol","title":"ChannelNotification","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelNotification"}],"abstract":[{"type":"text","text":"Notifications sent through the default "},{"type":"codeVoice","code":"NotificationCenter"},{"type":"text","text":" related to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel"},{"type":"text","text":" events."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelNotification"}],"url":"\/documentation\/aircoremedia\/channelnotification"},"doc://io.aircore.media/documentation/AircoreMedia/ChannelNotification/joinStateDidChange":{"role":"symbol","title":"joinStateDidChange","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinStateDidChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel\/JoinState-swift.enum"},{"type":"text","text":" has changed for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel"},{"type":"text","text":" associated with the notification’s "},{"type":"codeVoice","code":"object"},{"type":"text","text":"."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/ChannelNotification\/joinStateDidChange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinStateDidChange"}],"url":"\/documentation\/aircoremedia\/channelnotification\/joinstatedidchange"},"doc://io.aircore.media/documentation/AircoreMedia/Channel/JoinState-swift.enum":{"role":"symbol","title":"Channel.JoinState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinState"}],"abstract":[{"type":"text","text":"The states that represent the active status of a channel."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Channel\/JoinState-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoinState"}],"url":"\/documentation\/aircoremedia\/channel\/joinstate-swift.enum"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Channel\/title","value":"AIRChannel"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Channel\/fragments","value":[{"kind":"identifier","text":"AIRChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1ChannelNotification\/title","value":"AIRChannelNotification"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1ChannelNotification\/fragments","value":[{"kind":"identifier","text":"AIRChannelNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1ChannelNotification~1joinStateDidChange\/title","value":"joinStateDidChange"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1ChannelNotification~1joinStateDidChange\/fragments","value":[{"kind":"identifier","text":"joinStateDidChange"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}