{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera","preciseIdentifier":"c:@M@AircoreMedia@objc(cs)AIRCamera","text":"AIRCamera"},{"kind":"text","text":" * "},{"kind":"identifier","text":"camera"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/aircoremedia\/aircamerapreview\/camera"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AIRCameraPreview\/camera","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"The strongly-held camera object that this preview renders from."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"camera"}],"title":"camera","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@AircoreMedia@objc(cs)AIRCameraPreview(py)camera","modules":[{"name":"AircoreMedia"}],"navigatorTitle":[{"kind":"identifier","text":"camera"}]},"hierarchy":{"paths":[["doc:\/\/io.aircore.media\/documentation\/AircoreMedia","doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AIRCameraPreview"]]},"references":{"doc://io.aircore.media/documentation/AircoreMedia/AIRCameraPreview":{"role":"symbol","title":"AIRCameraPreview","fragments":[{"kind":"identifier","text":"AIRCameraPreview"}],"abstract":[{"type":"text","text":"An object that represents a preview of a "},{"type":"text","text":"Camera"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Used for rendering the video from a "},{"type":"text","text":"Camera"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AIRCameraPreview","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia\/aircamerapreview"},"doc://io.aircore.media/documentation/AircoreMedia/LocalStream":{"role":"symbol","title":"LocalStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalStream"}],"abstract":[{"type":"text","text":"An object representing a local stream that sends audio"}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalStream"}],"url":"\/documentation\/aircoremedia\/localstream"},"doc://io.aircore.media/documentation/AircoreMedia/Camera":{"role":"symbol","title":"Camera","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Camera"}],"abstract":[{"type":"text","text":"A representation of a Camera that can be used for previewing and publishing video for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/LocalStream"},{"type":"text","text":"."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/Camera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Camera"}],"url":"\/documentation\/aircoremedia\/camera"},"doc://io.aircore.media/documentation/AircoreMedia/AIRCameraPreview/camera":{"role":"symbol","title":"camera","fragments":[{"kind":"identifier","text":"camera"}],"abstract":[{"type":"text","text":"The strongly-held camera object that this preview renders from."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia\/AIRCameraPreview\/camera","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia\/aircamerapreview\/camera"},"doc://io.aircore.media/documentation/AircoreMedia":{"role":"collection","title":"AircoreMedia","abstract":[{"type":"text","text":"The Aircore Media SDK for iOS allows you to add high-quality, real-time voice and video chat to your iOS app quickly and easily, without the need to understand the complexities of building a real-time system on your own."}],"identifier":"doc:\/\/io.aircore.media\/documentation\/AircoreMedia","kind":"symbol","type":"topic","url":"\/documentation\/aircoremedia"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/title","value":"AIRLocalStream"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1LocalStream\/fragments","value":[{"kind":"identifier","text":"AIRLocalStream"}]},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Camera\/title","value":"AIRCamera"},{"op":"replace","path":"\/references\/doc:~1~1io.aircore.media~1documentation~1AircoreMedia~1Camera\/fragments","value":[{"kind":"identifier","text":"AIRCamera"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}